config/routes.rb
Rails.application.routes.draw do

	root to: 'pokedex#information'

	devise_for :users, path_names:{sign_in: 'login',sign_out: 'logout'}

	

	resources :user do
    	resources :pokemon, only: [:show,:index] do
    		member do
    			patch :liberate_pokemon
    			patch :edit_nickname
    			patch :compare_with
    		end
    	end

    	resources :pokedex, only: [:show, :index] do

    		collection do
				get :information
				post :add_pokemon_to_team
			end
			
		end
  	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord

	belongs_to :user

	validates :nickname, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pokemon

  after_create :assign_default_role 

  def assign_default_role
  	self.add_role(:user) if self.roles.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	include Pundit
	protect_from_forgery

	def after_sign_in_path_for(user)
		root_path
	end

end

app/controllers/concerns/home_controller.rb
class HomeController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]
	#after_action :verify_authorized
	def initialize(args)
		
	end
	
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def pokemons_index
		pokemons = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon?limit=20"))
		@pokemons = []
		pokemons['results'].each do |pokemon|
			#TODO filters y pokemons species(de la APi, para la descripcion pokedex)
			url = pokemon['url']
			pokemon = JSON.parse(RestClient.get(url))
			@pokemons << (Pokemons::PokemonDecorator.decorate(pokemon))
		end
		@pokemons
	end
	
	def show
		pokemon_names = ["bulbasaur","charmander","squirtle"]
		@pokemons = []
		pokemon_names.each do |pokemon|
			pokemon = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon/#{pokemon}"))
			@pokemons << (Pokemons::PokemonDecorator.decorate(pokemon))
		end
		@pokemons
	end

	def show_pokemon#TODO Cambiar nombre del show
		pokemon = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon/#{params[:id]}"))
		Pokemons::PokemonDecorator.decorate(pokemon)
	end

end

app/controllers/pokedex_controller.rb
class PokedexController < ApplicationController
	
	def index
		pokemons = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon?limit=16"))
		@pokemons = []
		@descriptions = []
		id=0
		pokemons['results'].each do |pokemon|
			url = pokemon['url']
			pokemon_temp = JSON.parse(RestClient.get(url))
			@pokemons << (Pokedex::PokedexDecorator.decorate(pokemon_temp))
			description = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon-species/#{pokemon['name']}"))
			@descriptions << Descriptions::DescriptionDecorator.decorate(description)
			id= id+1
		end
		@pokemons
	end
	
	def show
		pokemon = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon/#{params[:id]}"))
		@pokemon = Pokedex::PokedexDecorator.decorate(pokemon)
		description = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon-species/#{params[:id]}"))
		@description = Descriptions::DescriptionDecorator.decorate(description)
	end
	
	def information
		pokemon_names = [1,4,7]
		@pokemons = []
		@descriptions = []
		pokemon_names.each do |pokemon|
			pokemon_temp = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon/#{pokemon}"))
			@pokemons << (Pokedex::PokedexDecorator.decorate(pokemon_temp))
			description = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon-species/#{pokemon}"))
			@descriptions << Descriptions::DescriptionDecorator.decorate(description)
		end
		@pokemons
	end

	def add_pokemon_to_team
		pokemon = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon/#{params[:pokemon_id]}"))
		@pokemon = Pokedex::PokedexDecorator.decorate(pokemon)
		description = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon-species/#{params[:pokemon_id]}"))
		@description = Descriptions::DescriptionDecorator.decorate(description)
		nickname = params[:nickname]
		user = params[:user_id]
		#TODO create use case pokemon
		Pokemons::CreateUseCase.execute(pokemon: @pokemon, user: user, description: @description, nickname: nickname)
		redirect_to user_pokemon_index_path
	end

end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
	
	def index
		pokemons = ::Pokemons::SearchByUser.execute(user_id: current_user.id)
		@pokemons = Pokemons::PokemonDecorator.decorate_collection(pokemons)
	end

	def show
		pokemon = ::Base::Find.execute(klass: Pokemon,id: params[:id])

		@pokemon = Pokemons::PokemonDecorator.decorate(pokemon)
	end

	def liberate_pokemon
		::Pokemons::Liberate.execute(id: params[:id])
		redirect_to user_pokemon_index_path(user_id: current_user.id)
	end

	def edit_nickname
		pokemon = ::Base::Find.execute(klass: Pokemon,id: params[:id])
		nickname = params[:pokemon][:nickname]
		@pokemon = Pokemons::UpdateUseCase.execute(pokemon: pokemon, nickname: nickname)
		redirect_to user_pokemon_path(user_id: current_user.id, id: params[:id])
	end

	def compare_with
		pokemon = ::Base::Find.execute(klass: Pokemon,id: params[:id])
		pokemon_api = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon/#{params[:pokemon][:id]}"))
		@pokemon_api = Pokedex::PokedexDecorator.decorate(pokemon_api)
		@stats = Pokemons::ComparePokemonUseCase.execute(pokemon1: pokemon, pokemon_api: @pokemon_api)
		@pokemon = Pokemons::PokemonDecorator.decorate(pokemon)
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def show
		pokemons = JSON.parse(RestClient.get("https://pokeapi.co/api/v2/pokemon?limit=151&offset=0"))
	end
	
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/pokemons_index.html.erb
<div>
	<h1 class="text-primary pt-3">Pokedex</h1>
	<h2 class="text-secondary">-</h2>
	<div class="row no-margin center-elements pb-5">
		<%@pokemons.each do |pokemon| #TODO Habria que hacer otro render%>
			<div class="card center card-width">
			   <h2 class="card-title text-primary pt-3"><%=pokemon.name%>  Nº:<%=pokemon.num_pokedex%></h2>
			   <h3 class="text-primary">-</h3>
			  <div class="card-body">
				<%=image_tag pokemon.image, title: pokemon.name, 
					class: "img-pokemon-index"%>
			    <div class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</div>
			    <%#TODO boton a show del pokemon%>
			    <div class="mb-3 mt-5">
			    	<%=link_to "Show", pokemons_index_home_index_path(user_id: current_user.id), class:"button-primary p-3"%>
				</div>
			  </div>
			</div>
		<%end%>	

</div>

app/views/layouts/_footer.html.erb
<div id="footer">
    <div class="pull-right">
     Developed by Andrés Valiño
    </div>
    <div class="">
      <%= Settings.app_name ||= 'Andrés Valiño' %> &copy; <%= Time.now.year.to_s %> 
    </div>
</div>

app/views/layouts/_navigation.html.erb
<header>
      <nav class="navegador">
        <ul class="no-list row center-xs middle-xs mr-0">
          <li class="col-md"><h2 id="logo">PROJECT POKEMON</h2></li>
          <li class="col-md list"><%=link_to "Information", root_path, class:"link"%></li>
          <%if user_signed_in?%>
            <li class="col-md list">
              <%=link_to "Pokedex", user_pokedex_index_path(user_id: current_user.id), class:"link"%>
            </li>
            <li class="col-md list">
              <%=link_to "My PC", user_pokemon_index_path(user_id: current_user.id), class:"link"%>
            </li>
            <li class="col-md list">
              <%=link_to "Logout", destroy_user_session_path,method: :delete, class:"link"%>
            </li>
          <%else%>
            <li class="col-md list">
              <%=link_to "Login", new_user_session_path, class:"link"%>
            </li>
            <li class="col-md list">
              <%=link_to "Sign up", new_user_registration_path, class:"link"%>
            </li>
          <%end%>
        </ul>
      </nav>
    </header>

app/views/pokedex/_modal_form_catch_pokemon.erb
<div class="modal inmodal mt-5" id="block_user_modal" role="dialog" aria-hidden="true" data-backdrop="false" style="display: none;">
  <div class="modal-dialog">
    <%=form_with :url => add_pokemon_to_team_user_pokedex_index_path, id: "form-catch-pokemon" do |f|%>
      <div class="modal-content animated fadeIn">
        <div class="modal-header">
          <h4 class="modal-title text-primary">Congratulations. You catch a <%=@pokemon.name%>!</h4>
        </div>
        <div class="modal-body">
          <div id="error-send" class="text-danger"></div>
          <div class="row">
            <div class="form-group">
              <div class="col-sm-12">
                <%= f.label "Select a nickname to #{@pokemon.name}", class: "text-primary mt-3", id: "label-nickname-catched"%>
                <%= f.text_field :nickname, class: "form-control input-lg ",id: "nickname-pokemon-field", placeholder: "Choose its nickname" %>
              	<%= hidden_field_tag 'pokemon_id', @pokemon.num_pokedex %>
              </div>
            </div>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-white" data-dismiss="modal">Free it</button>
          <%= button_tag "Catch it", type:"button", class: 'btn btn-primary be-primary', id: 'catch-pokemon' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pokedex/index.erb
<div>
	<h1 class="text-primary pt-3">Pokedex</h1>
	<h2 class="text-secondary">-</h2>
	<div class="row no-margin center-elements pb-5">
		<% num = 0%>
		<%@pokemons.each do |pokemon| #TODO Habria que hacer otro render%>
			<div class="card center card-width">
			   <h2 class="card-title text-primary pt-3"><%=pokemon.name%>  Nº:<%=pokemon.num_pokedex%></h2>
			   <h3 class="text-primary">-</h3>
			  <div class="card-body">
				<%=image_tag pokemon.image, title: pokemon.name, 
					class: "img-pokemon-index"%>
			    <div class="card-text"><%= @descriptions.at(num).description %></div>
			    <%#TODO boton a show del pokemon%>
			    <div class="mb-3 mt-5">
			    	<%=link_to "Show", user_pokedex_path(user_id: current_user.id, id: pokemon.id), class:"btn button-primary p-3"%>
				</div>
			  </div>
			</div>
			<% num= num+1 %>
		<%end%>	

</div>

app/views/pokedex/show.erb
<div class="card card center-xs card-show container-fluid ">
	<h2 class="card-title text-primary "><%=@pokemon.name%>  Nº: <%=@pokemon.num_pokedex%></h2>
	<h3 class="text-secondary text-center mb-2">-</h3>
	<div class="row text-primary">
		<div class=" show-pokemon ml-5 col-lg-3">
			<span class=" text-primary">
				<%=image_tag @pokemon.image, title: @pokemon.name, 
							id: @pokemon.name, class: "img-pokemon-index"%>
			</span>
			<span class=" text-primary">
				<p>Type: <%= @pokemon.type_of_pokemon%></p>
				<p>Habitat: <%= @description.habitat%></p>
				<p>Capture rate: <%= @description.capture_rate%>%</p>
				<p>Base Happiness: <%= @description.base_happiness%></p>
			</span>
		</div>
		<div class=" show-pokemon  col-lg-8 text-center">
			<h2 class="text-secondary mb-3">Description</h2>
			<p><%= @description.description%></p>
			<h2 class="text-secondary mb-3">Base Stats</h2>
			<div class="row" style="text-align: center;">
				<% stats = ["HP","Attack","Special attack","Defense","Special defense","Speed "]%>
				<% num =0%>
				<% stats.each do |stat| %>
					<span class="col-lg-4"><%=stat%>: <%= @pokemon.stats(num: num)%></span>
					<% num = num+1%>
				<% end %>
			</div>
			<div class="row" style="text-align: center;">
				<div class=" col-lg-8">
					<h2 class="text-secondary mb-3 mt-5">Attacks</h2>
					<div class="row">
						<% attacks = ["First attack","Second attack","Third attack","Fourth attack"]%>
						<% num2 =0%>
						<% attacks.each do |attack| %>
							<span class="col-lg-6 mt-3"><%=attack%>: <%= @pokemon.attacks(num: num2)%></span>
							<% num2 = num2+1%>
						<% end %>
					</div>
				</div>
				<div class=" mt-5 col-lg-4 vertical-middle-align padded">
				    <%=link_to "Capture", user_pokedex_path(user_id: current_user.id, id: @pokemon.id), class:"btn button-primary p-3 align-middle vertical-middle-align", id:"try-catch-pokemon"%>
				</div>
			</div>
		</div>
	</div>
</div>

<%= render 'modal_form_catch_pokemon'%>

<script>


    $(function () {
        $('#try-catch-pokemon').on('click', function (e) {
        	e.preventDefault();
            $('#block_user_modal').modal('show');
        });

        $('#catch-pokemon').on('click', function (e){
        	if ($('#nickname-pokemon-field').val() == ""){
        		$('#error-send').html("Choose a name to <%=@pokemon.name%>");
        	}
        	else{
        		$('#form-catch-pokemon').submit();
        	}
        });

        $(document).keyup(function(e) {
		  if (e.keyCode === 13){
		  	if ($('#nickname-pokemon-field').val() == ""){
        		$('#error-send').html("Choose a nickname to <%=@pokemon.name%>");
        	}
        	else{
        		$('#form-catch-pokemon').submit();
        	} 	
		  }
		  if (e.keyCode === 27) $('#block_user_modal').modal('hide');
		});

    });

</script>

app/views/pokemon/_modal_delete_pokemon.html.erb
<div class="modal inmodal mt-5" id="delete_pokemon_modal" role="dialog" aria-hidden="true" data-backdrop="false" style="display: none;">
  <div class="modal-dialog">
      <div class="modal-content animated fadeIn">
        <div class="modal-header">
          <h4 class="modal-title text-primary">Free <%=@pokemon.nickname%></h4>
        </div>
        <div class="modal-body">
          <div id="error-send" class="text-danger"></div>
          <div class="row">
            <div class="form-group">
              <div class="col-sm-12">
                <div>Are you sure you want to change the nickname of <%=@pokemon.nickname%>?</div>
              </div>
            </div>
          </div>
        <div class="modal-footer">
          <%=form_with model: @pokemon, :url => liberate_pokemon_user_pokemon_path(user_id:current_user.id,id: @pokemon.id), id: "form-destroy-pokemon" do |f|%>
            <button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
            <%= button_tag "Free #{@pokemon.nickname}", type:"button", class: 'btn btn-primary be-primary', id: 'delete-pokemon' %>
          <% end %>
        </div>
      </div>

  </div>
</div>
</div>

app/views/pokemon/_modal_edit_nickname.html.erb
<div class="modal inmodal mt-5" id="edit_pokemon_modal" role="dialog" aria-hidden="true" data-backdrop="false" style="display: none;">
  <div class="modal-dialog">
    <%=form_with model: @pokemon, :url => edit_nickname_user_pokemon_path(user_id:current_user.id,id: @pokemon.id), id: "form-edit-pokemon", format: :js, method: :patch, remote: true do |f|%>
      <div class="modal-content animated fadeIn">
        <div class="modal-header">
          <h4 class="modal-title text-primary">Do you want to change the nickname?</h4>
        </div>
        <div class="modal-body">
          <div id="error-send" class="text-danger"></div>
          <div class="row">
            <div class="form-group">
              <div class="col-sm-12">
                <%= f.label "Are you sure that you want to change the nickname of #{@pokemon.name}", class: " mt-3 m-left", id: "label-nickname-edit"%>
                <%= f.text_field :nickname, class: "form-control input-lg ",id: "edit-nickname-pokemon-field", placeholder: "Choose its nickname" %>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
            <%= button_tag "Edit", type:"button", class: 'btn btn-primary be-primary', id: 'edit-pokemon' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pokemon/_modal_to_compare_pokemon.html.erb
<div class="modal inmodal mt-5" id="compare_pokemon_modal" role="dialog" aria-hidden="true" data-backdrop="false" style="display: none;">
  <div class="modal-dialog">
    <%=form_with model: @pokemon, :url => compare_with_user_pokemon_path(user_id:current_user.id,id: @pokemon.id), id: "form-compare-pokemon" do |f|%>
      <div class="modal-content animated fadeIn">
        <div class="modal-header">
          <h4 class="modal-title text-primary">Select a pokemon to compare</h4>
        </div>
        <div class="modal-body">
          <div id="error-send-compare" class="text-danger"></div>
          <div class="row">
            <div class="form-group">
              <div class="col-sm-12">
                <%= f.label "Num pokedex", class: "mt-3", id: "label-compare"%>
                <%= f.text_field :id, class: "form-control input-lg ",id: "edit-nickname-pokemon-field", placeholder: "Choose its nickname" %>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
            <%= button_tag "Compare", type:"button", class: 'btn btn-primary be-primary', id: 'compare-pokemon' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pokemon/compare_with.html.erb
<div class="card card center-xs card-show container-fluid ">
	<h2 id="nickname-h2"class="card-title text-primary "><%=@pokemon.nickname%><%= link_to edit_nickname_user_pokemon_path(user_id: current_user.id),id:"button-edit-nickname" do %>
    <i class="fa fa-pencil"></i>
  <% end %></h2>
	<h3 class="text-secondary text-center mb-4"><%=@pokemon.name%>  Nº: <%=@pokemon.num_pokedex%></h3>
	<div class="row text-primary">
		<div class=" show-pokemon ml-5 col-lg-3">
			<span class=" text-primary">
				<%=image_tag @pokemon.image, title: @pokemon.name, 
							id: @pokemon.name, class: "img-pokemon-index"%>
			</span>
			<span class=" text-primary">
				<p>Type: <%= @pokemon.type_of_pokemon%></p>
				<p>Habitat: <%= @pokemon.habitat%></p>
				<p>Base Happiness: <%= @pokemon.base_happiness%></p>
			</span>
		</div>
		<div class=" show-pokemon  col-lg-8 text-center">
			<h2 class="text-secondary mb-3">Description</h2>
			<p><%= @pokemon.description%></p>
			<h2 class="text-secondary mb-3">Base Stats</h2>
			<div class="row" style="text-align: center;">
				<span class="col-lg-4">HP: <%=@pokemon.hp%></span>
				<span class="col-lg-4">Attack: <%=@pokemon.atack%></span>
				<span class="col-lg-4">Special Attack: <%=@pokemon.special_atack%></span>
				<span class="col-lg-4">Defense: <%=@pokemon.defense%></span>
				<span class="col-lg-4">Special Defense: <%=@pokemon.special_defense%></span>
				<span class="col-lg-4">Speed: <%=@pokemon.speed%></span>
			</div>
			<div class="row" style="text-align: center;">
				<div class=" col-lg-7">
					<h2 class="text-secondary mb-3 mt-5">Attacks</h2>
					<div class="row">
						<span class="col-lg-6 mt-3">First attack: <%=@pokemon.atack0%></span>
						<span class="col-lg-6 mt-3">Second attack: <%=@pokemon.atack1%></span>
						<span class="col-lg-6 mt-3">Third attack: <%=@pokemon.atack2%></span>
						<span class="col-lg-6 mt-3">Fourth attack: <%=@pokemon.atack3%></span>
					</div>
				</div>
				<div class=" mt-5 col-lg-5 vertical-middle-align padded row">
					<div class="col-lg-6">
						<%=link_to "Liberate",liberate_pokemon_user_pokemon_path(user_id: current_user.id,id: @pokemon.id), id: "pokemon-#{@pokemon.id}", class:"btn btn-white p-3 align-middle vertical-middle-align", id:"button-to-modal-delete-pokemon"%>
					</div>
					<div class="col-lg-6">
						<%=link_to "Compare",liberate_pokemon_user_pokemon_path(user_id: current_user.id,id: @pokemon.id), id: "pokemon-#{@pokemon.id}", class:"btn btn-primary p-3 align-middle vertical-middle-align be-primary ", id:"button-to-modal-compare-pokemon"%>
					</div>
				    
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pokemon/index.erb
<div>
	<h1 class="text-primary pt-3">My PC</h1>
		<% if @pokemons.any?%>
		<h2 class="text-secondary">-</h2>
		<div class="row no-margin center-elements pb-5">
			<%@pokemons.each do |pokemon| %>
				<div class="card center card-width">
				   <h2 class="card-title text-primary pt-3"><%=pokemon.nickname%></h2>
				   <h2 class="card-title text-secondary pt-3"><%=pokemon.name%>  Nº:<%=pokemon.num_pokedex%></h2>
				  <div class="card-body">
					<%=image_tag pokemon.image, title: pokemon.name, 
						class: "img-pokemon-index"%>
				    <div class="card-text"><%= pokemon.description%></div>
				    <div class="mb-3 mt-5">
				    	<%=link_to "Show", user_pokemon_path(user_id: current_user.id, id: pokemon.id), class:"btn button-primary p-3"%>
					</div>
				  </div>
				</div>
			<%end%>
		<% else %>
			<h2 class="text-secondary mt-5">You dont have any pokemons</h2>
			<p><%=link_to "Pokedex", user_pokedex_index_path(user_id: current_user.id), class:"btn button-primary p-3 mt-5"%></p>
		<% end %>	

</div>

app/views/pokemon/show.html.erb
<div class="card card center-xs card-show container-fluid ">
	<h2 id="nickname-h2"class="card-title text-primary "><%=@pokemon.nickname%><%= link_to edit_nickname_user_pokemon_path(user_id: current_user.id),id:"button-edit-nickname" do %>
    <i class="fa fa-pencil"></i>
  <% end %></h2>
	<h3 class="text-secondary text-center mb-4"><%=@pokemon.name%>  Nº: <%=@pokemon.num_pokedex%></h3>
	<div class="row text-primary">
		<div class=" show-pokemon ml-5 col-lg-3">
			<span class=" text-primary">
				<%=image_tag @pokemon.image, title: @pokemon.name, 
							id: @pokemon.name, class: "img-pokemon-index"%>
			</span>
			<span class=" text-primary">
				<p>Type: <%= @pokemon.type_of_pokemon%></p>
				<p>Habitat: <%= @pokemon.habitat%></p>
				<p>Base Happiness: <%= @pokemon.base_happiness%></p>
			</span>
		</div>
		<div class=" show-pokemon  col-lg-8 text-center">
			<h2 class="text-secondary mb-3">Description</h2>
			<p><%= @pokemon.description%></p>
			<h2 class="text-secondary mb-3">Base Stats</h2>
			<div class="row" style="text-align: center;">
				<span class="col-lg-4">HP: <%=@pokemon.hp%></span>
				<span class="col-lg-4">Attack: <%=@pokemon.atack%></span>
				<span class="col-lg-4">Special Attack: <%=@pokemon.special_atack%></span>
				<span class="col-lg-4">Defense: <%=@pokemon.defense%></span>
				<span class="col-lg-4">Special Defense: <%=@pokemon.special_defense%></span>
				<span class="col-lg-4">Speed: <%=@pokemon.speed%></span>
			</div>
			<div class="row" style="text-align: center;">
				<div class=" col-lg-7">
					<h2 class="text-secondary mb-3 mt-5">Attacks</h2>
					<div class="row">
						<span class="col-lg-6 mt-3">First attack: <%=@pokemon.atack0%></span>
						<span class="col-lg-6 mt-3">Second attack: <%=@pokemon.atack1%></span>
						<span class="col-lg-6 mt-3">Third attack: <%=@pokemon.atack2%></span>
						<span class="col-lg-6 mt-3">Fourth attack: <%=@pokemon.atack3%></span>
					</div>
				</div>
				<div class=" mt-5 col-lg-5 vertical-middle-align padded row">
					<div class="col-lg-6">
						<%=link_to "Liberate",liberate_pokemon_user_pokemon_path(user_id: current_user.id,id: @pokemon.id), id: "pokemon-#{@pokemon.id}", class:"btn btn-white p-3 align-middle vertical-middle-align", id:"button-to-modal-delete-pokemon"%>
					</div>
					<div class="col-lg-6">
						<%=link_to "Compare",liberate_pokemon_user_pokemon_path(user_id: current_user.id,id: @pokemon.id), id: "pokemon-#{@pokemon.id}", class:"btn btn-primary p-3 align-middle vertical-middle-align be-primary ", id:"button-to-modal-compare-pokemon"%>
					</div>
				    
				</div>
			</div>
		</div>
	</div>
</div>


<%= render 'modal_delete_pokemon'%>
<%= render 'modal_edit_nickname'%>
<%= render 'modal_to_compare_pokemon'%>

<script>


    $(function () {

    	//Destroy
        $('#button-to-modal-delete-pokemon').on('click', function (e) {
        	e.preventDefault();
            $('#delete_pokemon_modal').modal('show');
        });

        $('#delete-pokemon').on('click', function (e){
        		$('#form-destroy-pokemon').submit();
        });

        //KeyBindings
        $(document).keyup(function(e) {
		  if (e.keyCode === 13){
        	$('#form-destroy-pokemon').submit();
		  }
		  if (e.keyCode === 27){ 
		  	$('#block_user_modal').modal('hide');
		  	$('#edit_pokemon_modal').modal('hide');
			}
		});

        //Edit
        $('#button-edit-nickname').on('click', function (e) {
        	e.preventDefault();
            $('#edit_pokemon_modal').modal('show');
        });

        $('#edit-pokemon').on('click', function (e){
        		$('#form-edit-pokemon').submit();
        });

        //Compare
        $('#button-to-modal-compare-pokemon').on('click', function (e) {
        	e.preventDefault();
            $('#compare_pokemon_modal').modal('show');
        });

        $('#compare-pokemon').on('click', function (e){
        		$('#form-compare-pokemon').submit();
        });

    });

</script>